### ISSUE TITLE
An Add feature  suggestion 

### ISSUE THREAD

**Issue by Mahuyo001** [Friendly0Fire/GW2Radial#84] opened 2019-03-08 00:53 UTC
Hi, i'm a big fan of you the mount mod, and i think that i have an idea that could help it further.
The idea, is (i will say) basic but to add a "Add" or "+" button to add another key. But i do see the difficulties in this in the slicing of a circle panel, and this could help out because you wouldn't have to keep on coming out with new versions every-time a new mount came out.
Bests

**Comment by Hoff16** [comment] 2019-03-08 16:01
You could also have it be an optional item, ala the Gryphon or Roller Beetle. Show up if you want it or hide it?

**Comment by Friendly0Fire** [comment] 2019-03-11 21:35
I'm planning on eventually adding fully customizable wheels, so I think that's just going to be part of the feature and I'll consider this to be a duplicate of #69.

**Closed by Friendly0Fire** 2019-03-11 21:35 UTC
