### ISSUE TITLE
Issues with d912pxy

### ISSUE THREAD

**Issue by unrelentingsarcasm** [Friendly0Fire/GW2Radial#210] opened 2021-09-14 10:39 UTC
Whether I'm using the current release or the 2.1.0-pre1, I am getting this pop up error dialog box that will not load the game.

![d912pxy error](https://user-images.githubusercontent.com/69797676/133242375-59411650-a959-4900-9b7f-bc1be01a770f.png)

I have made every .ini and config folder for d912pxy writable by all users.

I am not super computer literate and don't know if the language about increased integration used in the 2.1.0-pre1 notes is saying that I no longer need to load d912pxy or not.  Also, I am not using the Addon Manager because I multibox with ArcDPS, d912pxy, GW2Hook, and TacO (mainly for farming routes).  LaunchBuddy allows me to use all of those addons as injected software and load multiple clients.  I would love to use Radial and it seems like you are making dramatic steps to share your tool with the community, but is there a way to use all of those addons and multibox that is not LaunchBuddy (which it seems like will not be a supported launcher with Radial)?

UPDATE:  **I appear to have gotten all 4 of these to load in LB by renaming GW2 Radial to d3d9_chainload.dll, renaming d912pxy to d3d9_mchain.dll, and then use the injected software feature from LB to load GW2Hook.  I have yet to check this for full stability but all of the menus and ReShade settings are working.  To multibox, I'm going to ensure that LB uses unique mumble links for each account loaded.**

**Comment by Friendly0Fire** [comment] 2021-09-14 15:36
I don't use LaunchBuddy, so I don't know what it does, but it likely creates copies/hardlinks of config files which is causing issues with d912pxy. In theory, Radial should be compatible with any multibox app now that 2.1.0 supports renaming the MumbleLink mapping.

Since Radial does not seem to be the root cause for this issue, I'll close this now. I invite you to track this with d912pxy or LaunchBuddy itself. If you find that Radial is involved, please provide me with some additional details and feel free to reopen.

**Closed by Friendly0Fire** 2021-09-14 15:36 UTC

**Comment by unrelentingsarcasm** [comment] 2021-09-15 09:17
For another update, today I attempted to login and it appears everything works except for ArcDPS.  I don't really understand how that would be possible if ArcDPS's d3d9.dll is calling to the GW2Radial d3d9_chainload.dll, which in turn is loading the d912pxy d3d9_mchain.dll.  Any thoughts on what the interaction would be that would be keeping ArcDPS's functionality from working in game while it works enough to chainload all of the other .dlls?
