### ISSUE TITLE
Markers interaction options [bug]

### ISSUE THREAD

**Issue by SthepKnyght** [Friendly0Fire/GW2Radial#226] opened 2021-09-29 20:00 UTC
Using the latest update to GW2 Radial, the option to 'move cursor to original location after release' is always active, whether or not it is checked in the interaction options. That is only true for the Markers (location markers) and not the object markers.

It is not game breaking and will not lead to any crash, but it is exceedingly easy to reproduce. I have this bug with two different computers, both with the same version of GW2 Radial (this wasn't a problem before).

**Comment by Friendly0Fire** [comment] 2021-10-02 15:48
Duplicate of #236

**Closed by Friendly0Fire** 2021-10-02 15:48 UTC
Labels: bug
