### ISSUE TITLE
Could not save addon configuration. Reason given was: No such file or directory.

### ISSUE THREAD

**Issue by rl92** [Friendly0Fire/GW2Radial#273] opened 2022-01-31 17:58 UTC
Hi, As the title says, I'm getting the error when trying to use the addon.

I just installed the addon via GW2 addon manager.

Thanks.

**Comment by GGiry** [comment] 2022-01-31 18:33
I had the same issue here.

I fixed it by creating a file **config.ini** in the folder **...\Guild Wars 2\addons\gw2radial**

Until it is fixed.

**Comment by Friendly0Fire** [comment] 2022-01-31 18:37
Duplicate of #271.

**Closed by Friendly0Fire** 2022-01-31 18:37 UTC

**Comment by rl92** [comment] 2022-01-31 19:03
creating an empty config.ini file in that folder fixed it for me, sorry for the duplicate. Thanks.
