### ISSUE TITLE
Can't dismount with same keybind used to pull up radial menu.

### ISSUE THREAD

**Issue by BobotheHutt** [Friendly0Fire/GW2Radial#233] opened 2021-09-30 21:56 UTC
This use to be how it worked. I would open the radial menu with = and then use = again to dismount. With the new version, once I'm mounted, = does nothing and won't pull up the radial menu. I believe in the past, clicking the = while mounted would bring up the radial menu and the center area would use the keybind of the last mount you used therefore causing you dismount.

I can set the in game keybind for dismount but then I need two keybinds for something that use to require one.

**Comment by BobotheHutt** [comment] 2021-09-30 22:01
This use to be how it worked.  I would open the radial menu with = and then use = again to dismount.  With the new version, once I'm mounted, = does nothing and won't pull up the radial menu.   I believe in the past, clicking the = while mounted would bring up the radial menu and the center area would use the keybind of the last mount you used therefore causing you dismount.  

I can set the in game keybind for dismount but then I need two keybinds for something that use to require one.

**Comment by sicu** [comment] 2021-09-30 22:36
That's odd, I'm on the latest v2.1.0 as well and it works exactly like that. As long as I have already selected a mount in my current gaming session, tapping the radial hotkey while already mounted will dismount me. The radial select menu won't show while you're mounted though, it just yeets you off immediately. You need the following setting selected for the centre behaviour to work that way:
![radial settings](https://user-images.githubusercontent.com/26230029/135538736-c12c1c6f-7797-4e40-b951-c0a1ed5fd9de.jpg)

**Comment by sicu** [comment] 2021-09-30 22:38
Scratch that, it dismounts me regardless of what I have `Center behavior` set to.

**Comment by BobotheHutt** [comment] 2021-09-30 22:40
Interesting.  I wonder if I need to do a fresh install.  I just replaced the dll because I'm waiting for the dx11 stuff to get worked out before I swap to launcher buddy.  I have the same options selected as you do but yeah, nothing happens.

**Comment by sicu** [comment] 2021-09-30 22:44
Try to reset you keybinds in the radial settings since the update changed the way it handles inputs.
`Complete rewrite of keyboard input handling. This should hopefully fix all the keyboard layout issues for good. You may need to redefine certain keybinds after this update, sorry!`

**Comment by BobotheHutt** [comment] 2021-09-30 22:45
ok, so this is odd.  My problems when I first encountered this were on an alt account that does not have all the mounts unlocked.  I just tried in on my main and everything worked perfect.  I swapped back to another alt that also doesn't have all the mounts and same behavior as before where I couldn't dismount.

**Comment by sicu** [comment] 2021-09-30 22:48
Hmm, perhaps something to do with 'Visibility & Ordering' in the settings then. Do you have them all displayed? Perhaps try to only display the ones you have available on your alt account and try again?

**Comment by BobotheHutt** [comment] 2021-09-30 22:53
yes, that did fix this issue.  Unfortunately, the settings are the same for all accounts so I would need to toggle on and off the mounts I have for each account every time I swap.  Really not a big deal since I only care about playing on my main account and I now know how to make that work.

**Comment by sicu** [comment] 2021-09-30 22:58
True, but it was good to narrow down what the problem was. Don't close this issue though, we'll wait for FriendlyFire to weigh in on if or how he wants to handle it :)

**Comment by BobotheHutt** [comment] 2021-09-30 23:01
sounds good.  Thanks for narrowing it down.

**Comment by MiryksV** [comment] 2021-10-01 00:45
I can confirm that that I have exactly the same problem on my alt account. On my main account with all mounts, while mounting, I unmount ez by pressing again on my keybind on my mouse but with my alt account with few mounts, need to press on my keyboard.
Quite sure that the stable v1.2.4 didn't have this problem

Besides, amazing job and bravo for the new version

**Comment by Canyonbydesign** [comment] 2021-10-01 00:51
I am having the same issue (Alt accounts without all Mounts not being able to dismount). The last release did not have this issue.

**Comment by Friendly0Fire** [comment] 2021-10-01 00:55
The behavior is implemented as follows: when you're mounted and press your keybind, the first "active" (that is, with a keybind set and visible in the menu) mount keybind is sent to the game. If you have the mount enabled, that will dismount you.

What I'll do instead is always use your last used mount, which should be set any time you want to dismount. In the rare cases where that isn't true, it'll fall back to the first active mount as before.

**Closed** 2021-10-01 00:56 UTC

**Comment by MiryksV** [comment] 2021-10-01 06:05
Thanks for the fix !
