### ISSUE TITLE
Crash on GW2 exit

### ISSUE THREAD

**Issue by tildebyte** [Friendly0Fire/GW2Radial#295] opened 2022-03-01 02:59 UTC
**Describe the bug**
As $SUBJECT

**To Reproduce**
1. Exit Guild Wars 2 😉

**Expected behavior**
No crash on exit

**System configuration (please fill in):**
 - OS: Windows 11
 - GPU: RTX2070
 -  GW2Radial loaded via Addon Loader

**Attachments**
- [config.ini.zip](https://github.com/Friendly0Fire/GW2Radial/files/8158459/config.ini.zip)
- gw2radial.log is empty
- [gw2al_log.txt](https://github.com/Friendly0Fire/GW2Radial/files/8158434/gw2al_log.txt)
- [GW2_crash.log](https://github.com/Friendly0Fire/GW2Radial/files/8158432/GW2_crash.log)
- [Crash.dmp.zip](https://github.com/Friendly0Fire/GW2Radial/files/8158442/Crash.dmp.zip)

**Comment by DreamsUnderStars** [comment] 2022-03-01 16:14
I get the same thing happening everytime I exit.

**Comment by Wrthlor** [comment] 2022-03-08 03:49
Been getting the error as well since EoD release - reproduced on closing game
- Game completely crashes when only use gw2radial (plus _addon loader_ and _d3d wrapper_)
- Produces "Intercepted Unhandled Exception" when paired with ArcDPS

Addon loader log
- [gw2al_log.txt](https://github.com/Friendly0Fire/GW2Radial/files/8202573/gw2al_log.txt)

**Comment by Friendly0Fire** [comment] 2022-03-19 17:26
I've been unable to reproduce this issue with just GW2Radial, but I get it consistently with arcdps in D3D11, regardless of whether GW2Radial is installed.

Can you all (@Wrthlor @DreamsUnderStars @tildebyte) confirm whether you get this crash with arcdps and/or without arcdps?

**Comment by Wrthlor** [comment] 2022-03-19 21:29
@Friendly0Fire Was able to reproduce the errors. Same situation that I had mentioned earlier. Only checked when dealing with DX11

Versions used:
- GW2Radial v2.2.1 (2022-02-28)
- ArcDPS 2022-03-16
- loader-core v1.1 (2021-09-27)
- d3d9_wrapper v2.0 (2021-09-25)

All scenarios done with loader-core and d3d9_wrapper installed, played with DX11, and exiting from in-game and from character selection screen (denoted as 1 and 2 in files respectively). Scenarios done:
- **GW2Radial only**
  - Crash occurs on exit
  - [GW2Radial.zip](https://github.com/Friendly0Fire/GW2Radial/files/8310159/GW2Radial.zip)

- **GW2Radial + ArcDPS**
  - Produces *Intercepted unhandled exception in GW2 process. Game will terminate when this box is closed*
  - [ArcDPS+GW2radial.zip](https://github.com/Friendly0Fire/GW2Radial/files/8310161/ArcDPS%2BGW2radial.zip)

- **ArcDPS only**
  - No errors produced on exit

**Comment by Friendly0Fire** [comment] 2022-03-19 21:52
@Wrthlor Thank you!

Can you run with GW2Radial only using this version? [gw2addon_gw2radial.zip](https://github.com/Friendly0Fire/GW2Radial/files/8310194/gw2addon_gw2radial.zip)

You should get a `.dmp` file in the main GW2 directory after the crash. You'll want to give that to me, ideally through Discord since it can contain some information about your PC.

**Comment by voidburn** [comment] 2022-03-19 22:27
Got some dump(s), all created on the same crash
[Dumps.zip](https://github.com/Friendly0Fire/GW2Radial/files/8310238/Dumps.zip)
.

**Comment by Wrthlor** [comment] 2022-03-19 22:51
@Friendly0Fire 
Just tested with the version you provided. Getting the same crash.
What's the Discord to sue to send the dump files?

**Comment by Wrthlor** [comment] 2022-03-21 01:12
Already told Friendly0Fire via Discord, but found a temporary(?) solution to this. 

Running GW2 in compatibility mode for Windows 7 or 8 has resulted in zero crashes. I didn't bother trying compatibility mode for Vista (and it's service packs). 

Quick glances at the crash logs point culprit at DX11 (it is "beta" still) as I have no issues with it in DX9. Maybe as ANet works on DX11, might occur less and less. Still might be something that can be fixed on GW2Radial's side, but unsure.

**Comment by voidburn** [comment] 2022-03-21 11:03
I wouldn't mind using dx9 and dx912pxy again, but gw2radial doesn't seem to work now unless dx11 is enabled. Will try compatibility mode in the meantime.

-------- Original Message --------

**Comment by ben-alkov** [comment] 2022-03-22 20:29
There's a dx9 fork of Radial

**Comment by Friendly0Fire** [comment] 2022-03-22 21:02
The DirectX 9 fork is temporary and won't be maintained, please don't direct people to it if at all possible.

**Comment by ben-alkov** [comment] 2022-03-23 00:43
> The DirectX 9 fork is temporary and won't be maintained, please don't direct people to it if at all possible.

Sorry bout that, didn't realize

**Comment by sekullbe** [comment] 2022-03-28 02:26
I have the same issue if you need more logs and/or crash dumps for diagnosis.

**Comment by Snaid1** [comment] 2022-03-28 17:04
same issue, although I did some experimenting and it only seems to crash if I have arcdps and/or reshade enabled too. to detail my experiences:

arcdps: no crash
gw2radial: no crash
Reshade: no crash
arcdps + Reshade: no crash
arcdps + gw2radial: CRASH!
gw2radial + Reshade: CRASH!
ALL 3: CRASH!

seems like gw2radial is causing issues and doesn't want to play nice with other plugins. 
I'm on WIndows 10 with dx11 turned on. All plugins were installed using the UOAOM addon loader.

**Comment by Rockgod70** [comment] 2022-03-28 22:48
I ONLY have gw2Radial installed and it happens most times I exit.

**Comment by sambilbow** [comment] 2022-03-30 12:39
Also experiencing exactly this on Windows 11

> 
>     * **GW2Radial only**
>       
>       * Crash occurs on exit
> 
>     * **GW2Radial + ArcDPS**
>       
>       * Produces _Intercepted unhandled exception in GW2 process. Game will terminate when this box is closed_
> 
>     * **ArcDPS only**
>       
>       * No errors produced on exit

**Comment by Friendly0Fire** [comment] 2022-04-02 03:17
To all having issues, try [this](https://github.com/Friendly0Fire/GW2Radial/suites/5903172300/artifacts/201010597) new build. You'll have to manually install by just replacing the existing dll in `addons/gw2radial`.

**Comment by sambilbow** [comment] 2022-04-02 07:01
> To all having issues, try [this](https://github.com/Friendly0Fire/GW2Radial/suites/5903172300/artifacts/201010597) new build. You'll have to manually install by just replacing the existing dll in `addons/gw2radial`.

Instant crash on character load for me with this release. Where can I find appropriate logs to attach?

**Comment by sekullbe** [comment] 2022-04-02 11:31
The nightly build works for me- no crashes on load or exit and no unusual notes in the standard logs.

**Comment by Friendly0Fire** [comment] 2022-04-02 14:00
> > To all having issues, try [this](https://github.com/Friendly0Fire/GW2Radial/suites/5903172300/artifacts/201010597) new build. You'll have to manually install by just replacing the existing dll in `addons/gw2radial`.
> 
> Instant crash on character load for me with this release. Where can I find appropriate logs to attach?

There should be `.dmp` files in the main GW2 install directory and a `gw2radial.log` file as well.

**Comment by voidburn** [comment] 2022-04-02 14:35
> To all having issues, try [this](https://github.com/Friendly0Fire/GW2Radial/suites/5903172300/artifacts/201010597) new build. You'll have to manually install by just replacing the existing dll in `addons/gw2radial`.

Still crashing with 2.2r1, log file is empty and no crash dumps are present (except for the gw2 one). Only gw2radial, addon loader and d3d wrapper installed:

```
[INFO] core | Addon loader v1.0 (v1.1 r33) initialized
[INFO] core | Loading addons from "./addons" path
[INFO] core | Loading d3d9_wrapper
[INFO] core | Loaded d3d9_wrapper v2.0 r21
[INFO] core | Loading gw2radial
[INFO] core | Loaded gw2radial v2.2 r1
[INFO] core | Done loading addons
[INFO] d3d9_wrapper | Loading system dxgi
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system d3d11
```

**Comment by Friendly0Fire** [comment] 2022-04-02 14:53
> no crash dumps are present (except for the gw2 one)

@voidburn I could try to look at the GW2 dump, it'll at least let me know if the crash is the same as before.

**Comment by voidburn** [comment] 2022-04-02 14:58
Here it is:  [Crash.zip](https://github.com/Friendly0Fire/GW2Radial/files/8402759/Crash.zip)

**Comment by Friendly0Fire** [comment] 2022-04-02 15:02
Thank you! This unfortunately doesn't tell me much, but it might be a different crash now. Since I see you're running an AMD GPU and I know most of the crashes reported here also happened on an AMD GPU, I'll wait and see if the pattern persists. If that's the case, we might be facing two issues (one which I encountered myself with `MMDevAPI.dll` and which this nightly might resolve, and another with AMD drivers which I have yet to figure out).

**Comment by Snaid1** [comment] 2022-04-02 15:05
> To all having issues, try [this](https://github.com/Friendly0Fire/GW2Radial/suites/5903172300/artifacts/201010597) new build. You'll have to manually install by just replacing the existing dll in `addons/gw2radial`.

Tried this nightly build and it fixed the issue for me. seems to be working perfectly now. thanks!

**Comment by sambilbow** [comment] 2022-04-02 15:17
> > > To all having issues, try [this](https://github.com/Friendly0Fire/GW2Radial/suites/5903172300/artifacts/201010597) new build. You'll have to manually install by just replacing the existing dll in `addons/gw2radial`.
> > 
> > 
> > Instant crash on character load for me with this release. Where can I find appropriate logs to attach?
> 
> @sambilbow There should be `.dmp` files in the main GW2 install directory and a `gw2radial.log` file as well.

Similar to @voidburn, empty log file. Only Crash.dmp present. AMD card here too

[Crash.zip](https://github.com/Friendly0Fire/GW2Radial/files/8402790/Crash.zip)
.

**Comment by Wrthlor** [comment] 2022-04-02 16:41
> To all having issues, try [this](https://github.com/Friendly0Fire/GW2Radial/suites/5903172300/artifacts/201010597) new build. You'll have to manually install by just replacing the existing dll in `addons/gw2radial`.

Same results as previous tests and other nightly builds. Win8 compatibility mode still works with no crashes. Win10 "mode" produces identical results: 
* GW2Radial only - crashes
* GW2Radial+ArcDPS - "unhandled exception in GW2 process"

Sent the crash files on Discord

**Comment by voidburn** [comment] 2022-04-08 20:41
I found something that might give additional clues:

If I have `gw2radial` + `arcdps` + `arcdps boon table` or `arcdps killproof.me` installed the instant I push either `alt + shift + b` or `alt + shift + k` to open either of the arc dps plugins the game instantly (and silently) crashes to desktop.

Without gw2radial installed it doesn't happen.

**Comment by nscha** [comment] 2022-05-14 18:34
Since moving to newest GW2Radial and DX11 I've been experiencing a crash on exit as well. Since I wasn't using DX11 before I tested removing all addons (compared all files with someone that never installed addons to make sure there was no extra dll left over) and was able to confirm using DX11 without addons does not cause the crash.

Having only GW2Radial installed (via Addon Manager) I see the crash window on exit each and every time. (I have never installed arcdps so I'm 100% sure it's never been there)

gw2al_log.txt contents:
```
[INFO] core | Addon loader v1.0 (v1.1 r33) initialized
[INFO] core | Loading addons from "./addons" path
[INFO] core | Loading d3d9_wrapper
[INFO] core | Loaded d3d9_wrapper v2.0 r21
[INFO] core | Loading gw2radial
[INFO] core | Loaded gw2radial v2.2 r1
[INFO] core | Done loading addons
[INFO] d3d9_wrapper | Loading system dxgi
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system d3d11
```

Crash details:
```
*--> Crash <--*
Exception: c0000005  
Memory at address 00000209`557f2ec8 could not be read
App: Gw2-64.exe 
Pid: 4560
BaseAddr: 00007FF7192A0000
ProgramId: 101
Build: 128878
Module: atidxx64.dll
When: 2022-05-14T18:21:11Z 2022-05-14T15:21:11-03:00
Uptime:   0 days  0:03:28
Flags: 0
DumpFile: Crash.dmp

*--> System <--*
Name: 058493db
IpAddr: 192.168.0.102
Processors: 4 [GenuineIntel:6:12:3]
OSVersion: Windows 10.0 (64 bit)

*--> System Memory <--*
Physical: 10989MB/16325MB  67%
Paged:     8101MB/18757MB  43%
Virtual:  134209265MB/134217727MB  3%
Load: 32%
CommitTotal:  10655MB
CommitLimit:  18757MB
CommitPeak:   13906MB
SystemCache:   5630MB
HandleCount:  82843
ProcessCount:   215
ThreadCount:   2049

*--> Process Memory <--*
Private:         1862MB
WorkingSet:       182MB
PeakWorkingSet:  2725MB
PageFaults:   3580995
...
*--> DllList <--*
00007FF7192A0000 - H:\Games\Guild Wars 2\Gw2-64.exe
00007FFBB5290000 - C:\WINDOWS\SYSTEM32\ntdll.dll
00007FFBB4720000 - C:\WINDOWS\System32\KERNEL32.DLL
00007FFBB29E0000 - C:\WINDOWS\System32\KERNELBASE.dll
00007FFBB3D80000 - C:\WINDOWS\System32\USER32.dll
00007FFBB29B0000 - C:\WINDOWS\System32\win32u.dll
00007FFBB4540000 - C:\WINDOWS\System32\GDI32.dll
00007FFBB3150000 - C:\WINDOWS\System32\gdi32full.dll
00007FFBB2F10000 - C:\WINDOWS\System32\msvcp_win.dll
00007FFBB2CB0000 - C:\WINDOWS\System32\ucrtbase.dll
00007FFBB3F20000 - C:\WINDOWS\System32\ADVAPI32.dll
00007FFBB3CE0000 - C:\WINDOWS\System32\msvcrt.dll
00007FFBB4F30000 - C:\WINDOWS\System32\sechost.dll
00007FFBB3930000 - C:\WINDOWS\System32\RPCRT4.dll
00007FFBB5110000 - C:\WINDOWS\System32\WS2_32.dll
00007FFBB3030000 - C:\WINDOWS\System32\WINTRUST.dll
00007FFBB3A60000 - C:\WINDOWS\System32\PSAPI.DLL
00007FFBB3AD0000 - C:\WINDOWS\System32\ole32.dll
00007FFBB41E0000 - C:\WINDOWS\System32\combase.dll
00007FFBB5180000 - C:\WINDOWS\System32\OLEAUT32.dll
00007FFBB47E0000 - C:\WINDOWS\System32\SHELL32.dll
00007FFBB2DB0000 - C:\WINDOWS\System32\CRYPT32.dll
00007FFBAC6D0000 - C:\WINDOWS\SYSTEM32\VERSION.dll
00007FFBACEB0000 - C:\WINDOWS\SYSTEM32\WTSAPI32.dll
00007FFBA78F0000 - C:\WINDOWS\SYSTEM32\WINMM.dll
00007FFBA1120000 - C:\WINDOWS\SYSTEM32\MSACM32.dll
00007FFB93D30000 - C:\WINDOWS\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.1566_none_91a49058cc87e409\gdiplus.dll
00007FFB7EE30000 - C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll
00007FFB7EE10000 - C:\WINDOWS\SYSTEM32\USP10.dll
00007FFBA10C0000 - C:\WINDOWS\SYSTEM32\MSIMG32.dll
00007FFB9B290000 - C:\WINDOWS\SYSTEM32\Secur32.dll
00007FFB9B1C0000 - C:\WINDOWS\SYSTEM32\winmmbase.dll
00007FFBB2380000 - C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
00007FFBB2870000 - C:\WINDOWS\SYSTEM32\SSPICLI.DLL
00007FFBB4100000 - C:\WINDOWS\System32\IMM32.DLL
00007FFBB2590000 - C:\WINDOWS\SYSTEM32\MSASN1.dll
00007FFBB3260000 - C:\WINDOWS\System32\bcryptPrimitives.dll
00007FFBAB4B0000 - C:\WINDOWS\SYSTEM32\dbghelp.dll
00007FFBB0AE0000 - C:\WINDOWS\SYSTEM32\windows.storage.dll
00007FFBB2410000 - C:\WINDOWS\SYSTEM32\Wldp.dll
00007FFBB32F0000 - C:\WINDOWS\System32\SHCORE.dll
00007FFBB3A70000 - C:\WINDOWS\System32\shlwapi.dll
00007FFBB28F0000 - C:\WINDOWS\SYSTEM32\profapi.dll
00007FFBB08E0000 - C:\WINDOWS\SYSTEM32\kernel.appcore.dll
00007FFBB2FB0000 - C:\WINDOWS\System32\bcrypt.dll
00007FFBB02A0000 - C:\WINDOWS\system32\uxtheme.dll
00007FFBA7F30000 - C:\WINDOWS\SYSTEM32\dxcore.dll
00007FFBB2FE0000 - C:\WINDOWS\System32\cfgmgr32.dll
00007FFBB3FD0000 - C:\WINDOWS\System32\clbcatq.dll
00007FFBB16B0000 - C:\WINDOWS\SYSTEM32\ntmarta.dll
00007FFB98590000 - C:\WINDOWS\system32\napinsp.dll
00007FFB98570000 - C:\WINDOWS\system32\pnrpnsp.dll
00007FFB9D430000 - C:\WINDOWS\system32\wshbth.dll
00007FFBAE710000 - C:\WINDOWS\system32\NLAapi.dll
00007FFBB1E10000 - C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
00007FFBB2170000 - C:\WINDOWS\System32\mswsock.dll
00007FFBB1E50000 - C:\WINDOWS\SYSTEM32\DNSAPI.dll
00007FFBB4140000 - C:\WINDOWS\System32\NSI.dll
00007FFB98430000 - C:\WINDOWS\System32\winrnr.dll
00007FFBA7E50000 - C:\WINDOWS\System32\fwpuclnt.dll
00007FFBA89D0000 - C:\Windows\System32\rasadhlp.dll
00007FFBB33A0000 - C:\WINDOWS\System32\msctf.dll
00007FFBA5560000 - C:\WINDOWS\SYSTEM32\textinputframework.dll
00007FFBAFBC0000 - C:\WINDOWS\System32\CoreUIComponents.dll
00007FFBAFF20000 - C:\WINDOWS\System32\CoreMessaging.dll
00007FFBAE5B0000 - C:\WINDOWS\SYSTEM32\wintypes.dll
00007FFBA9EE0000 - C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
00007FFBA3100000 - C:\WINDOWS\SYSTEM32\TextShaping.dll
00007FFB80DB0000 - H:\Games\Guild Wars 2\bin64\CoherentUI64.dll
00007FFBADD30000 - H:\Games\Guild Wars 2\bin64\d3d9.dll
00007FFB99580000 - C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
00007FFBB2360000 - C:\WINDOWS\SYSTEM32\CRYPTSP.dll
00007FFBB1A80000 - C:\WINDOWS\system32\rsaenh.dll
00007FFBB3C60000 - C:\WINDOWS\System32\imagehlp.dll
00007FFBB1290000 - C:\WINDOWS\SYSTEM32\gpapi.dll
00007FFB9B4F0000 - C:\Windows\System32\cryptnet.dll
00007FFBACF20000 - C:\WINDOWS\SYSTEM32\WINNSI.DLL
00007FFBB1720000 - C:\WINDOWS\SYSTEM32\WINSTA.dll
00007FFBA7F70000 - H:\Games\Guild Wars 2\d3d11.dll
00007FFB9B3C0000 - H:\Games\Guild Wars 2\dxgi.dll
00007FFB9B3A0000 - H:\Games\Guild Wars 2\addonLoader.dll
00007FFB994E0000 - C:\WINDOWS\SYSTEM32\MSVCP140.dll
00007FFB99570000 - C:\WINDOWS\SYSTEM32\VCRUNTIME140_1.dll
00007FFB9A780000 - H:\Games\Guild Wars 2\addons\d3d9_wrapper\gw2addon_d3d9_wrapper.dll
00007FFB20810000 - H:\Games\Guild Wars 2\addons\gw2radial\gw2addon_gw2radial.dll
00007FFBA2020000 - C:\WINDOWS\SYSTEM32\WININET.dll
00007FFBAE770000 - C:\WINDOWS\SYSTEM32\D3DCOMPILER_47.dll
00007FFBB12C0000 - C:\WINDOWS\system32\dxgi.dll
00007FFBAEBD0000 - C:\WINDOWS\system32\d3d11.dll
00007FFBA7920000 - C:\WINDOWS\System32\DriverStore\FileRepository\u0377495.inf_amd64_58cc395c0bf03a26\B377432\aticfx64.dll
00007FFBA7720000 - C:\WINDOWS\System32\DriverStore\FileRepository\u0377495.inf_amd64_58cc395c0bf03a26\B377432\atiuxp64.dll
00007FFBA57B0000 - C:\WINDOWS\System32\DriverStore\FileRepository\u0377495.inf_amd64_58cc395c0bf03a26\B377432\atidxx64.dll
00007FFBB34C0000 - C:\WINDOWS\System32\SETUPAPI.dll
00007FFBB0160000 - C:\WINDOWS\SYSTEM32\apphelp.dll
00007FFBA3CD0000 - C:\WINDOWS\SYSTEM32\amdihk64.dll
00007FFBAF5E0000 - C:\WINDOWS\SYSTEM32\dcomp.dll
00007FFBB0700000 - C:\WINDOWS\SYSTEM32\dwmapi.dll
00007FFBA4010000 - C:\WINDOWS\SYSTEM32\iertutil.dll
00007FFB94DA0000 - C:\WINDOWS\SYSTEM32\ondemandconnroutehelper.dll
00007FFBA9DD0000 - C:\WINDOWS\SYSTEM32\winhttp.dll
00007FFBB27B0000 - C:\WINDOWS\SYSTEM32\DPAPI.DLL
00007FFBA3AC0000 - C:\WINDOWS\SYSTEM32\urlmon.dll
00007FFBA3A90000 - C:\WINDOWS\SYSTEM32\srvcli.dll
00007FFBB1F20000 - C:\WINDOWS\SYSTEM32\netutils.dll
00007FFBB19A0000 - C:\WINDOWS\system32\schannel.DLL
00007FFB9BE00000 - C:\WINDOWS\SYSTEM32\mskeyprotect.dll
00007FFBB2440000 - C:\WINDOWS\SYSTEM32\NTASN1.dll
00007FFBB2480000 - C:\WINDOWS\SYSTEM32\ncrypt.dll
00007FFB9BE50000 - C:\WINDOWS\system32\ncryptsslp.dll
00007FFBAC760000 - C:\WINDOWS\System32\MMDevApi.dll
00007FFBB2750000 - C:\WINDOWS\System32\DEVOBJ.dll
00007FFB81440000 - C:\WINDOWS\SYSTEM32\wdmaud.drv
00007FFBAD5C0000 - C:\WINDOWS\SYSTEM32\AVRT.dll
00007FFBAD890000 - C:\WINDOWS\SYSTEM32\ksuser.dll
00007FFBAC540000 - C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
00007FFBB1F30000 - C:\WINDOWS\SYSTEM32\powrprof.dll
00007FFBB1DF0000 - C:\WINDOWS\SYSTEM32\UMPDC.dll
00007FFBA17F0000 - C:\WINDOWS\SYSTEM32\msacm32.drv
00007FFBA1450000 - C:\WINDOWS\SYSTEM32\midimap.dll
00007FFBB04E0000 - C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
00007FFBA9A30000 - C:\WINDOWS\SYSTEM32\mscms.dll
00007FFBA9A10000 - C:\WINDOWS\SYSTEM32\ColorAdapterClient.dll
00007FFBB28B0000 - C:\WINDOWS\SYSTEM32\USERENV.dll
00007FFB7F7B0000 - C:\WINDOWS\SYSTEM32\icm32.dll

[DbgHelp.dll is C:\WINDOWS\SYSTEM32\dbghelp.dll]
[DbgHelp.dll version 6.2.19041.867 (64/32-bit compatible)]
...
*--> Error Logs <--*
18:18:15Z NULL REWARD TRACK: EC159E18-259B-E211-8756-78E7D1936222
18:18:15Z NULL REWARD TRACK: EC159E18-259B-E211-8756-78E7D1936222
18:18:15Z NULL REWARD TRACK: EC159E18-259B-E211-8756-78E7D1936222
18:18:18Z Model '0x039279': Permutation 'w' not found, auto selecting permutation
18:18:22Z Texture missing mip chain: 0x00f980
18:18:22Z Texture missing mip chain: 0x00f982
18:18:47Z NULL REWARD TRACK: EC159E18-259B-E211-8756-78E7D1936222
18:18:47Z NULL REWARD TRACK: EC159E18-259B-E211-8756-78E7D1936222
18:18:47Z NULL REWARD TRACK: EC159E18-259B-E211-8756-78E7D1936222
18:18:47Z Content is referencing a propID that doesn't exist propId='2248714043770673416'
18:18:47Z Content is referencing a propID that doesn't exist propId='1972964328275477224'
18:18:53Z Model '0x22e30d': Permutation 'stoweda' not found, auto selecting permutation
18:18:58Z Texture '0x213587' dimensions too small
18:18:58Z Loading '0x213587' texture failed
18:18:58Z Texture '0x213588' dimensions too small
18:18:58Z Loading '0x213588' texture failed
18:19:02Z Texture missing mip chain: 0x0f8c78
18:19:24Z Content is referencing a propID that doesn't exist propId='1924002649382879764'
18:19:51Z Texture '0x213597' dimensions too small
18:19:51Z Loading '0x213597' texture failed
18:19:51Z Texture '0x213598' dimensions too small
18:19:51Z Loading '0x213598' texture failed
18:20:00Z Model '0x20a990': Permutation 'stoweda' not found, auto selecting permutation
18:20:01Z Texture missing mip chain: 0x01350d
Crashed at 18:21:11Z
```

I am too using an AMD GPU, it's an RX 570, with updated software 22.3.1

Please let me know if there is any more info that might help.

**Comment by Wrthlor** [comment] 2022-06-29 04:26
Decided to give it another "thorough" test now that DX11 is official (no longer beta)... Still crashing. Same responses as previously mentioned: 

> 
>     * **GW2Radial only**
>       
>       * Crash occurs on exit
> 
>     * **GW2Radial + ArcDPS**
>       
>       * Produces _Intercepted unhandled exception in GW2 process. Game will terminate when this box is closed_
> 
>     * **ArcDPS only**
>       
>       * No errors produced on exit
>

Versions used: 
- GW2Radial v2.2.1 (2022-02-28)
- ArcDPS 2022-06-28
- loader-core v1.1 (2021-09-27)
- d3d9_wrapper v2.0 (2021-09-25)

Everything installed _manually_


And just like previously mentioned, all combinations in Windows 8 compatibility mode produces **NO** problems.

**Comment by quickbeamed** [comment] 2022-07-19 21:50
Any updates on this? I still have this bug using addon manager + gw2 radial + arcdps

**Comment by Friendly0Fire** [comment] 2022-08-21 22:02
Please try the new pre-release to assess if this is still present.

**Comment by Wrthlor** [comment] 2022-08-22 02:46
Unfortunately, getting the same results as [previously mentioned above](https://github.com/Friendly0Fire/GW2Radial/issues/295#issuecomment-1169519698). 

- Win10 x64, AMD RX580 8GB (latest driver)
- **GW2Radial v2.3.0-pre5** (2022-08-21)
- loader-core v1.1 (2021-09-27)
- d3d9_wrapper v2.0 (2021-09-25)
- ArcDPS 2022-08-02 

GW2Radial Only:
- Crashes upon exit: log out from character select screen, exit to desktop from in-game menu

GW2Radial + ArcDPS:
- Unhandled exception irregardless of closing method

Again, all issues arise when using default GW2 settings (no compatibility mode). 
However, as soon as Windows 8 compatibility mode is used, no crashes occur.

**Comment by Friendly0Fire** [comment] 2022-08-22 03:05
Well crap. Unfortunately, I don't have an AMD GPU to test this with, so I'd need someone else with some graphics programming experience who also encounters this crash to take a look.

**Comment by nscha** [comment] 2022-08-22 03:56
It sounds like for Wrthlor it is 100% reproducible every time, but that's not my experience, sometimes I get the crash on exit, sometimes I don't. I always exit directly to desktop from logged in character, and I don't use ArcDPS. I do have AMD.

After installing the Version 2.3.0 Pre-release 5 I actually started and exited the game 3 or 4 times before the crash happened again 😢

```
*--> Crash <--*
Exception: c0000005  
Memory at address 00000229`1bbdc910 could not be read
App: Gw2-64.exe 
Pid: 3780
BaseAddr: 00007FF7F4130000
ProgramId: 101
Build: 132525
Module: atidxx64.dll
When: 2022-08-22T03:46:31Z 2022-08-22T00:46:31-03:00
Uptime:   0 days  0:19:38
Flags: 0
DumpFile: Crash.dmp
```

**Comment by Friendly0Fire** [comment] 2022-08-24 15:41
I need to isolate things further since I'm getting reports of AMD GPU users without crashing issues.

@nscha @Wrthlor @sambilbow (and any other with an AMD GPU) Can you please confirm your OS, GPU model, and driver version?

**Comment by Wrthlor** [comment] 2022-08-24 16:01
@Friendly0Fire when I was testing on 2022-08-21:

- OS: _Windows 10, Version 21H2 (OS Build 19044.1889)_
- GPU: _Sapphire Nitro+ Radeon RX 580 8GB GDDR5_
- GPU Driver: _31.0.12019.5007_ 
- GPU Software: _Adrenaline Edition Version 22.8.1_

**Comment by sambilbow** [comment] 2022-08-24 17:37
@Friendly0Fire when I was testing (haven't played recently, so probably around May)
- OS: _Windows 11_
- GPU: _Sapphire Nitro+ Radeon RX 590 8GB GDDR5_
- GPU Driver: _30.0.15021.7000_
- GPU Software: _Adrenalin Edition Version 22.4.2_

**Comment by Friendly0Fire** [comment] 2022-08-24 17:43
Ok, looks like it's a GCN specific bug then. I'll have to see what I can do, thanks!

**Comment by nscha** [comment] 2022-08-25 23:49
Sorry for the delay @Friendly0Fire , adding my details although I think it only confirms what you already noticed

OS: Windows 10 Pro 21H2 Build 19044.1706
GPU: Radeon RX 570 Series 5G DDR5 
Driver: AMD Software Adrenalin Edition Version 31.0.12015.1008

**Comment by midadami** [comment] 2022-08-28 10:04
OS: Windows 10 Pro 21H2 Build 19044.1889
GPU: Sapphire Nitro+ Radeon RX 5700 XT 8GB GDDR6
Driver: AMD Software Adrenalin Edition Version 22.8.2

**Comment by Friendly0Fire** [comment] 2022-09-08 04:30
Alright, I have a new build for all AMD users!

Please try the following and let me know if it resolves your issues: https://github.com/Friendly0Fire/GW2Radial/suites/8187385854/artifacts/356177320

Many thanks to @cheahjs for the assistance in figuring this one out.

**Comment by Rockgod70** [comment] 2022-09-08 04:54
Just as some additional info for you, I have Win11 and Radial is my only add-on.

I also have an AMD chipset GPU.

I have not had any crashes for the past 3 months or so.

**Comment by Hinnful** [comment] 2022-09-08 08:47
OS: Windows 11 (also had Win10 with the same issue)
GPU: Sapphire RX 580 4GB
Driver: AMD Software Adrenalin Edition Version 22.8.2

**New (nightly) build:** 
Immediately crashes the game when selecting any mount via addon. Selecting a mount with native game UI works normal

**Version 2.3.0 Pre-release 7:** 
Works normal. Sometimes I get an exit crash but I can't figure out the circumstances. Happens like once in 5-6 launches.
Also got 1 crash mid-game but again can't figure out exactly why

**Comment by Friendly0Fire** [comment] 2022-09-08 14:59
@Hinnful do you have dumps I can take a look at?

**Comment by Wrthlor** [comment] 2022-09-08 18:32
> Alright, I have a new build for all AMD users!
> 
> Please try the following and let me know if it resolves your issues: https://github.com/Friendly0Fire/GW2Radial/suites/8187385854/artifacts/356177320
> 
> Many thanks to @cheahjs for the assistance in figuring this one out.

Specs:
- OS: _Windows 10, Version 21H2 (OS Build 19044.1889)_
- GPU: _Sapphire Nitro+ Radeon RX 580 8GB GDDR5_
- GPU Driver: _31.0.12019.9007_ 
- GPU Software: _Adrenaline Edition Version 22.8.2_

Add-ons: 
- **GW2Radial**: _nightly-b723ba176afe36a39717acc95739d67bd6317d2f_
- ArcDPS: _20220827.215851-452-x64_
- loader-core and d3d9_wrapper [still the same](https://github.com/Friendly0Fire/GW2Radial/issues/295#issuecomment-1221729197)

Results:
- No issues using radial in-game. No crashes or errors when logging out or exiting to desktop (in world and character selection screen)
- Note: Windows 10 (no compatibility) and Windows 8 compatibility mode both function with no errors
- Note2: Using only GW2Radial and GW2Radial+ArcDPS combination both function with no errors

Other:
- Can provide some of the auto generated dumps if you need/want them. 
- BlishHUD appears to have no issues with GW2Radial as expected - injection vs overlay

**Comment by Friendly0Fire** [comment] 2022-09-08 18:55
@Wrthlor If the addon still generates dumps in spite of everything working correctly, I would appreciate if you could upload a few of them so I can check what's causing them, but I'm glad it's working for you!

**Comment by nscha** [comment] 2022-09-08 23:38
> Please try the following and let me know if it resolves your issues: https://github.com/Friendly0Fire/GW2Radial/suites/8187385854/artifacts/356177320
I downloaded and tested this version and got a crash while trying to mount up for the first time. 

@Friendly0Fire I see this new artifact includes a pdb file, as well as the gw2addon_gw2radial.dll file, that I hadn't seen before in other nightlies. 
Should I have put that pdb file inside the gw2radial directory as well?

**Comment by Friendly0Fire** [comment] 2022-09-08 23:43
@nscha No, the PDB file is debugging information which is useful to me (and other potential contributors) but unnecessary for users.

If you got dumps from this crash, please upload them or DM them to me on Discord so I can look into it.

**Comment by nscha** [comment] 2022-09-09 01:06
> If you got dumps from this crash, please upload them or DM them to me on Discord so I can look into it.
sent over Discord @Friendly0Fire 👍

**Comment by Friendly0Fire** [comment] 2022-09-09 02:02
@Hinnful New build to hopefully fix this crash: https://github.com/Friendly0Fire/GW2Radial/suites/8206968771/artifacts/357483050

**Comment by Friendly0Fire** [comment] 2022-09-11 17:42
Well as far as I can tell, the latest nightly fixes this issue, so I will close this.

If you still encounter a crash *with the nightly on an AMD GPU*, feel free to reopen.

**Closed by Friendly0Fire** 2022-09-11 17:42 UTC
Labels: bug
