### ISSUE TITLE
"Show on mouse" keybind does not properly clear.

### ISSUE THREAD

**Issue by BoyangJ** [Friendly0Fire/GW2Radial#237] opened 2021-10-02 07:45 UTC
**Describe the bug**
The "show on mouse" keybind does not get properly cleared, and furthermore causes the radial menu to appear and become permanently stuck on the screen.

**To Reproduce**
1. Click "set" and bind "show on mouse" to any key.
2. Click "set", then click "clear".
3. Observe that nothing is now showing as bound for "show on mouse", even if the options menu is closed and re-opened.
4. Press the key that was previously bound in step 1.
5. Observe that the radial menu still appears, and cannot be closed, and no options can be selected either.
6. Even after the game is restarted, upon opening the options menu, you can observe that the keybind set in step 1 reappeared, even though it was cleared in step 2.

**Expected behavior**
On step 4, pressing the key that was previously bound but then cleared should not open the radial menu.
Furthermore, even if the menu does appear, it should not become stuck permanently on the screen.

**Screenshots**

**System configuration (please fill in):**
 - OS: Windows 10
 - GPU: RTX 2080 SUPER
 - Chainloading: arcdps -> GW2Radial

**Additional context**
This issue occurred on v2.1.0.
All other functionality of the addon appears to work correctly.

**Comment by sicu** [comment] 2021-10-02 10:47
This seems to be a duplicate of the issue that was being tracked here: https://github.com/Friendly0Fire/GW2Radial/issues/229
A fix was committed and will probably come in the next release.

**Comment by Friendly0Fire** [comment] 2021-10-02 14:30
Duplicate of #229

**Closed by Friendly0Fire** 2021-10-02 14:30 UTC
